var CONFIG = {
    BANNER_INTERVAL: 4000,
    BANNER_BG_SCALE_INTERVAL: 2000,
    FRESH_HERO_INTERVAL: 5000,
    LOADING_DURATION: 2500,
    CURSOR_SIZE: 32,
    MINI_PLAYER_GAP: 20,
    COMET_MAX_PARTICLES: 40,
    COMET_SPAWN_INTERVAL: 16,
    CODE_COUNTDOWN_SECONDS: 60,
    API_BASE: '/api',
    DISC_COVER_MIN_WIDTH: 800,
    DISC_COVER_MIN_HEIGHT: 800
};